In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [68]:
# Load the csv exported in Part I to a DataFrame
city_data = pd.read_csv("../WeatherPy/output_data/cities.csv")
city_data.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,chuy,-33.6971,-53.4616,70.09,96.0,2.0,6.24,UY,1.611454e+09
1,vaini,-21.2000,-175.2000,78.80,94.0,75.0,8.05,TO,1.611454e+09
2,dikson,73.5069,80.5464,-16.96,90.0,69.0,7.07,RU,1.611454e+09
3,provideniya,64.3833,-173.3000,7.03,84.0,1.0,2.01,RU,1.611454e+09
4,yellowknife,62.4560,-114.3525,-24.00,75.0,1.0,3.44,CA,1.611454e+09

In [130]:
# Configure gmaps.
gmaps.configure(api_key=g_key)

# Use the Lat and Lng as locations and Humidity as the weight.
locations = city_data[['Lat','Lng']]
weights = city_data['Humidity']
fig = gmaps.figure(map_type='SATELLITE',center=[0,0],zoom_level=2)

# Add Heatmap layer to map.
heatmap_layer = gmaps.heatmap_layer(locations, weights=weights, dissipating=False, max_intensity=250, point_radius=3)
fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [103]:
# Narrow down the cities to fit weather conditions.
# A max temperature lower than 80 degrees but higher than 70.
ideal_1 = city_data.loc[city_data['Max Temp'] > 70]
ideal_2 = ideal_1.loc[ideal_1['Max Temp'] < 80]

# Wind speed less than 10 mph.
ideal_3 = ideal_2.loc[ideal_2['Wind Speed'] < 10]

# Zero cloudiness.
ideal_final = ideal_3.loc[ideal_3['Cloudiness'] == 0]

# Drop any rows will null values.
ideal_final.dropna(how='any')

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
98,nueva gerona,21.8833,-82.8000,72.48,77.0,0.0,5.44,CU,1.611454e+09
124,san luis,-33.2950,-66.3356,79.48,34.0,0.0,7.67,AR,1.611454e+09
128,mar del plata,-38.0023,-57.5575,78.80,78.0,0.0,9.22,AR,1.611454e+09
145,san lorenzo,-25.3333,-57.5333,77.00,88.0,0.0,4.61,PY,1.611454e+09
234,cruzeiro do sul,-29.5128,-51.9853,72.00,92.0,0.0,1.01,BR,1.611454e+09
279,grand gaube,-20.0064,57.6608,77.00,82.0,0.0,1.01,MU,1.611454e+09
400,robertsport,6.7533,-11.3686,78.94,83.0,0.0,7.90,LR,1.611454e+09
404,harper,4.3750,-7.7169,77.81,87.0,0.0,7.34,LR,1.611454e+09
539,srivardhan,18.0333,73.0167,71.37,75.0,0.0,5.91,IN,1.611454e+09
552,ban nahin,18.2418,104.2122,75.99,50.0,0.0,0.81,LA,1.611454e+09

In [126]:
# Store into variable named hotel_df.
hotel_df = ideal_final

# Add a "Hotel Name" column to the DataFrame.
hotel_df.loc[:,'Hotel Name'] = ''

# Set parameters to search for hotels with 5000 meters.
params = {
    "keyword": "hotel",
    "radius": 5000,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Hit the Google Places API for each city's coordinates.
for index, row in hotel_df.iterrows():
    target_lat = row['Lat']
    target_lng = row['Lng']

    # add keyword to params dict
    params['location'] = f"{target_lat},{target_lng}"

    # assemble url and make API request
    print(f"Finding hotel in: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    # Store the first Hotel result into the DataFrame.
    try:
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
    except (KeyError,IndexError):
        print("Missing field/result... skipping.")
        
# Plot markers on top of the heatmap.

/Users/thomasbabjak/opt/anaconda3/envs/pythondata/lib/python3.9/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

Finding hotel in: nueva gerona.
Finding hotel in: san luis.
Finding hotel in: mar del plata.
Finding hotel in: san lorenzo.
Finding hotel in: cruzeiro do sul.
Finding hotel in: grand gaube.
Finding hotel in: robertsport.
Finding hotel in: harper.
Finding hotel in: srivardhan.
Finding hotel in: ban nahin.
Missing field/result... skipping.

In [127]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [128]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))